### ISSUE TITLE
Error on adding a Thing

### ISSUE THREAD

**Issue by stevoland** [insin/isomorphic-lab#1]
Hi, this is great stuff.

I get a strange error when trying to add a thing:

```
Error cleaning Form.name:connect ECONNREFUSED
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
POST /api/things 500 3.103 ms - -
```

Any ideas?

**Comment by insin** [comment]
I haven't encountered it yet, but will look at turning that into a proper error on the client.

**Comment by ghost** [comment]
It seems your /api/things service is not up and running. Crosscheck and try again.

**Comment by jmjpro** [comment]
working now
