### ISSUE TITLE
form reverts to browser default validation upon submit

### ISSUE THREAD

**Issue by jmjpro** [insin/isomorphic-lab#2]
I forced a validation error by adding a price greater than 100. I saw the custom validation error. Cool. Then I submitted the form with the price still greater than 100. I also got a validation error. Cool. What's not cool is that the validation error from the submission was a browser default validation error instead of a custom error.
![isomorphic-form-error](https://cloud.githubusercontent.com/assets/3256717/5958915/456e726a-a7d2-11e4-9a68-09b64151f296.png)

**Comment by insin** [comment]
Looks like we should enhance the client version adding `novalidate` on the `<form>` when the component mounts.

**Comment by insin** [comment]
Fixed in 1bdf9a2e20dfc0248514018f350b11a0f0fbc659 and deployed
