### ISSUE TITLE
Use in production?

### ISSUE THREAD

**Issue by duro** [insin/isomorphic-lab#3]
I like your implementation for it's simplicity. I was evaluating use of a Flux style architecture, and just kept feeling like I was adding so much boilerplate, and many implementations did not support an isomorphic implementation.

The app I am building is primarily a content browsing site, that will fetch data from a Wordpress backed API. We want it to have SPA feel, animation, and functionality.

With all that said, have you deployed your implementation to production? As the app grows have you found any issues that I should be aware of? Has this project moved beyond just experimentation and could I feel comfortable using it for a customer facing deployment?

**Comment by insin** [comment]
If it's the _approach_ you're asking about and you're comfortable with it (it more joining the dots than rocket science), go for it.

I would be happy to use - but haven't used - it in production, but would need to address things like caching first.

Everything is still very fluid in the land of all things isomorphic at the moment. People seem to be making their own stacks for it available daily and reusable libraries for different bits of it (like [react-resolver](https://github.com/ericclemmons/react-resolver) for `fetchData` type stuff) are appearing.

**Comment by revskill10** [comment]
The code is too complicated !
One benefit of this approach is for simpler development and maintainence. What's the point of complexing everything to get the same result ?
